### ISSUE TITLE
Does not compile on Windows with MSVC due to unistd.h

### ISSUE THREAD

**Issue by jgulotta** [bamonroe/tree-sitter-rnoweb#1]
I have tree-sitter set to install everything and I am currently using the MSVC toolchain. This is the only grammar that fails for me with this error:

> fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

I glanced through `scanner.c` for why it needs `unistd.h` but I didn't notice anything that should require this header - maybe `stdint.h` would be its replacement if it can't be removed?

**Comment by bamonroe** [comment]
Sorry for the delay, I'll take a look at this over the weekend.

**Comment by bamonroe** [comment]
Looks like it was totally unnecessary.

**Comment by jgulotta** [comment]
Confirmed it compiles and installs for me now, thanks!

**Comment by bamonroe** [comment]
No problem, please let me know if you find anything weird
